Repository SpiGes/handbook, pull requests merged in 2025-01, with the labels that each got.

#190 189 add infos faq
  content/de/FAQ/Falldaten/9_kostentrager_fall.md
  content/de/FAQ/technische_fragen/2_format_fehlermeldung.md
  content/fr/FAQ/Falldaten/9_kostentrager_fall.md
  content/fr/FAQ/technische_fragen/2_format_fehlermeldung.md
  content/it/FAQ/Falldaten/9_kostentrager_fall.md
  content/it/FAQ/technische_fragen/2_format_fehlermeldung.md
  static/img/grund_wiedereintritt_erreur.png
  static/img/vide_correct.png
  static/img/vide_faux.png
Labels: documentation

#191 Update version
  CHANGELOG.md
  RELEASE_NOTES.md
  hugo.toml
Labels: dependencies

#195 Release: New version + release notes/changelog updated
  CHANGELOG.md
  RELEASE_NOTES.md
  hugo.toml
Labels: release
